version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t service-broker-mock .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" != "release" ]; then
              if [ "${CIRCLE_PROJECT_USERNAME}" == "akkeris" ]; then 
                docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
                docker tag service-broker-mock "docker.io/akkeris/service-broker-mock:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                docker push "docker.io/akkeris/service-broker-mock:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  docker tag service-broker-mock "docker.io/akkeris/service-broker-mock:release-${CIRCLE_BUILD_NUM}"
                  docker tag service-broker-mock "docker.io/akkeris/service-broker-mock:latest"
                  docker push "docker.io/akkeris/service-broker-mock:latest"
                  docker push "docker.io/akkeris/service-broker-mock:release-${CIRCLE_BUILD_NUM}"
                fi
              fi
            fi

